export const TYPESENSE = {
  // replace with your own key for local development (see /frontend/README.md)
  DEV: 'VGpTTFZCMXdwL1pnUXBzc1VCRkxjdlMwZ200YTJGNlJEWk0rVDVtKzh5Yz01RDFseyJxdWVyeV9ieSI6InRleHQiLCJncm91cF9ieSI6ImVwaXNvZGUiLCJncm91cF9saW1pdCI6MTAsInNvcnRfYnkiOiJlcGlzb2RlOmFzYyIsInVzZV9jYWNoZSI6dHJ1ZSwiY2FjaGVfdHRsIjozNjAwfQ==',
  PROD: 'eUpwRFNJQXBhaDVoQ0Z1dkU3ZGRwUVlZRUc3aGxwbHJ1VXp5Uy9EdHZFOD10WllNeyJxdWVyeV9ieSI6InRleHQiLCJncm91cF9ieSI6ImVwaXNvZGUiLCJncm91cF9saW1pdCI6MTAsInNvcnRfYnkiOiJlcGlzb2RlOmFzYyIsInVzZV9jYWNoZSI6dHJ1ZSwiY2FjaGVfdHRsIjozNjAwfQ==',
}
