export const TYPESENSE = {
  // replace with your own key for local development (see /frontend/README.md)
  DEV:  'ay96SlROL1g4MDA5NGF1NlJqOEphTUJzNEh3czJNcnZ2dk42RnlZcmx2Zz1FRjA5eyJxdWVyeV9ieSI6InRleHQiLCJncm91cF9ieSI6ImVwaXNvZGUiLCJncm91cF9saW1pdCI6MTAsInNvcnRfYnkiOiJlcGlzb2RlOmFzYyIsInVzZV9jYWNoZSI6dHJ1ZSwiY2FjaGVfdHRsIjozNjAwfQ==',
  PROD: 'MzhzTnE0bEJLbE1oc2FvV3J5ZnliOEs2WUJNb3hOcjhrbW9ma0NheG5TZz1sM2lFeyJxdWVyeV9ieSI6InRleHQiLCJncm91cF9ieSI6ImVwaXNvZGUiLCJncm91cF9saW1pdCI6MTAsInNvcnRfYnkiOiJlcGlzb2RlOmFzYyIsInVzZV9jYWNoZSI6dHJ1ZSwiY2FjaGVfdHRsIjozNjAwfQ=='
}